In [ ]:
import pandas as pd

# Load your dataset 
df = pd.read_csv(r"D:\Data_D\TMU\MRP\1.0.Dataset\Socio_Economic\Census_Data_-_Selected_socioeconomic_indicators_in_Chicago,_2008_–_2012_20260425.csv")

# Check columns
df.columns

In [ ]:
selected_df = df[[
    'Community Area Number',
    'COMMUNITY AREA NAME',
    'PER CAPITA INCOME ',
    'PERCENT AGED 16+ UNEMPLOYED',
    'PERCENT HOUSEHOLDS BELOW POVERTY',
    'PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA'
]]

selected_df.head()

In [ ]:
selected_df = selected_df.rename(columns={
    'Community Area Number': 'community_area',
    'COMMUNITY AREA NAME': 'community_name',
    'PER CAPITA INCOME ': 'per_capita_income',
    'PERCENT AGED 16+ UNEMPLOYED': 'unemployment_rate',
    'PERCENT HOUSEHOLDS BELOW POVERTY': 'poverty_rate',
    'PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA': 'no_highschool_pct'
})

selected_df.head()

In [ ]:
final_df = selected_df[[
    'community_area',
    'community_name',
    'per_capita_income',
    'unemployment_rate',
    'no_highschool_pct'
]]

final_df.head()

In [ ]:
final_df = final_df.dropna(subset=['community_area'])

final_df.shape

In [ ]:
final_df['community_area'] = final_df['community_area'].astype(int)

final_df.dtypes

In [ ]:
final_df.shape

In [ ]:
df_2014 = pd.read_csv(r"D:\Data_D\TMU\MRP\1.0.Dataset\Socio_Economic\comarea.csv")
df_2014.columns

In [ ]:
df_2014_selected = df_2014[[
    'ComAreaID',
    'community',
    'PerCInc14',
    'Unemp14',
    'NoHS14'
]]

df_2014_selected.head()

In [ ]:
df_2014_selected['unemployment_rate'] = (df_2014['Unemp14'] / df_2014['LaborFrc']) * 100

df_2014_selected['no_highschool_pct'] = (df_2014['NoHS14'] / df_2014['Pop2014']) * 100

df_2014_selected.head()

In [ ]:
df_2014_selected = df_2014[[
    'ComAreaID',
    'community',
    'PerCInc14'
]].copy()

df_2014_selected['unemployment_rate'] = (df_2014['Unemp14'] / df_2014['LaborFrc']) * 100
df_2014_selected['no_highschool_pct'] = (df_2014['NoHS14'] / df_2014['Pop2014']) * 100

df_2014_selected.head()

In [ ]:
df_2014_selected = df_2014_selected.rename(columns={
    'ComAreaID': 'community_area',
    'community': 'community_name',
    'PerCInc14': 'per_capita_income'
})

df_2014_selected.head()

In [ ]:
df_2014_selected['community_area'] = df_2014_selected['community_area'].astype(int)

df_2014_selected.dtypes

In [ ]:
df_2020 = pd.read_csv(r"D:\Data_D\TMU\MRP\1.0.Dataset\Socio_Economic\Chicago_2020_sdoh.csv")
df_2020.columns

In [ ]:
[col for col in df_2020.columns if 'inc' in col.lower()]

In [ ]:
[col for col in df_2020.columns if 'unemp' in col.lower()]

In [ ]:
[col for col in df_2020.columns if 'hs' in col.lower()]

In [ ]:
[col for col in df_2020.columns if 'white' in col.lower()]

In [ ]:
df_2020_selected = df_2020[[
    'area_num_1',
    'community',
    'INCPERCAP',
    'Unemprt',
    'LT_HS'
]]

df_2020_selected.head()

In [ ]:
df_2020_selected['no_highschool_pct'] = (df_2020['LT_HS'] / df_2020['TOT_POP']) * 100

df_2020_selected['unemployment_rate'] = df_2020['Unemprt']

df_2020_selected.head()

In [ ]:
df_2020_selected = df_2020_selected[[
    'area_num_1',
    'community',
    'INCPERCAP',
    'unemployment_rate',
    'no_highschool_pct'
]].copy()

df_2020_selected = df_2020_selected.rename(columns={
    'area_num_1': 'community_area',
    'community': 'community_name',
    'INCPERCAP': 'per_capita_income'
})

df_2020_selected.head()

In [ ]:
df_2020_selected['community_area'] = df_2020_selected['community_area'].astype(int)

df_2020_selected.dtypes

In [ ]:
final_df['year'] = '2012'
df_2014_selected['year'] = '2014'
df_2020_selected['year'] = '2020'

In [ ]:
socio_final = pd.concat([final_df, df_2014_selected, df_2020_selected], ignore_index=True)

socio_final.head()

In [ ]:
socio_final.shape

In [ ]:
socio_final = socio_final.sort_values(by=['community_area', 'year'])

socio_final.head(10)

In [ ]:
socio_final.to_csv(r"D:\Data_D\TMU\MRP\1.0.Dataset\Socio_Economic\Socio_Economic_Final.csv", index=False)

In [46]:
crime_df = pd.read_csv(r"D:\Data_D\TMU\MRP\1.0.Dataset\Crime\Crime_2001_2023_Cleaned.csv")
socio_final = pd.read_csv(r"D:\Data_D\TMU\MRP\1.0.Dataset\Socio_Economic\Socio_Economic_Final.csv")
crime_df.columns

Index(['ID', 'Date', 'Primary Type', 'Description', 'Location Description',
       'Arrest', 'Domestic', 'Beat', 'District', 'Community Area', 'FBI Code',
       'Year', 'Latitude', 'Longitude', 'month', 'day_of_week', 'hour',
       'is_weekend'],
      dtype='object')

In [47]:
# Rename for consistency
crime_df = crime_df.rename(columns={
    'Community Area': 'community_area',
    'Year': 'year'
})

In [48]:
# Period 1 → use 2012 socio data
period_1 = crime_df[crime_df['year'] <= 2012].copy()

# Period 2 → use 2014 socio data
period_2 = crime_df[(crime_df['year'] >= 2013) & (crime_df['year'] <= 2016)].copy()

# Period 3 → use 2020 socio data
period_3 = crime_df[crime_df['year'] >= 2017].copy()

In [49]:
socio_2012 = socio_final[socio_final['year'] == 2012].copy()
socio_2014 = socio_final[socio_final['year'] == 2014].copy()
socio_2020 = socio_final[socio_final['year'] == 2020].copy()

In [50]:
socio_2012 = socio_2012.drop(columns=['year'])
socio_2014 = socio_2014.drop(columns=['year'])
socio_2020 = socio_2020.drop(columns=['year'])

In [51]:
merged_1 = period_1.merge(socio_2012, on='community_area', how='left')
merged_2 = period_2.merge(socio_2014, on='community_area', how='left')
merged_3 = period_3.merge(socio_2020, on='community_area', how='left')

In [52]:
final_merged_df = pd.concat([merged_1, merged_2, merged_3], ignore_index=True)

final_merged_df.head()

,ID,Date,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,community_area,...,Latitude,Longitude,month,day_of_week,hour,is_weekend,community_name,per_capita_income,unemployment_rate,no_highschool_pct
0,6255892,2008-05-17 18:00:00,ROBBERY,ARMED - HANDGUN,RESIDENCE,0,0,511,5.0,49,...,41.710040,-87.624796,5,5,18,1,Roseland,17949.0,20.3,16.9
1,6272641,2008-05-27 01:00:00,ROBBERY,STRONG ARM - NO WEAPON,STREET,0,1,512,5.0,49,...,41.703007,-87.625785,5,1,1,0,Roseland,17949.0,20.3,16.9
2,6438609,2008-08-05 22:37:00,ROBBERY,ARMED - HANDGUN,SCHOOL - PUBLIC GROUNDS,0,0,523,5.0,53,...,41.664425,-87.639053,8,1,22,0,West Pullman,16563.0,19.4,20.5
3,6680276,2008-12-27 20:00:00,BURGLARY,FORCIBLE ENTRY,RESIDENCE - GARAGE,0,0,1622,16.0,11,...,41.987326,-87.770650,12,5,20,1,Jefferson Park,27751.0,12.4,13.4
4,13209443,2004-09-17 00:00:00,OFFENSE INVOLVING CHILDREN,AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,RESIDENCE,0,1,935,9.0,61,...,41.808292,-87.637870,9,4,0,0,New City,12765.0,23.0,41.5

In [53]:
final_merged_df[['per_capita_income', 'unemployment_rate', 'no_highschool_pct']].isnull().sum()

per_capita_income    76
unemployment_rate    76
no_highschool_pct    76
dtype: int64

In [54]:
missing_rows = final_merged_df[final_merged_df['per_capita_income'].isnull()]

missing_rows['community_area'].value_counts()

community_area
0    76
Name: count, dtype: int64

In [55]:
final_merged_df = final_merged_df[final_merged_df['community_area'] != 0]

In [56]:
final_merged_df[['per_capita_income', 'unemployment_rate', 'no_highschool_pct']].isnull().sum()

per_capita_income    0
unemployment_rate    0
no_highschool_pct    0
dtype: int64

In [57]:
final_merged_df['community_area'].min(), final_merged_df['community_area'].max()

(1, 77)

In [58]:
final_merged_df.to_csv(
    r"D:\Data_D\TMU\MRP\1.0.Dataset\Final_Crime_Socio_Merged.csv",
    index=False
)

# Weather Data

In [60]:
weather_df = pd.read_csv(r"D:\Data_D\TMU\MRP\1.0.Dataset\Weather\4301028.csv")

weather_df.head()

,STATION,NAME,DATE,AWND,PRCP,SNOW,SNWD,TMAX,TMIN
0,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2001-01-01,7.61,0.0,0.0,17.0,24,5
1,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2001-01-02,8.50,0.0,0.0,15.0,19,5
2,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2001-01-03,11.41,0.0,0.0,14.0,28,7
3,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2001-01-04,11.63,0.0,0.0,14.0,30,19
4,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2001-01-05,13.87,0.0,0.0,13.0,36,21

In [ ]:
weather_df = weather_df.rename(columns={'DATE': 'date'})

weather_df['date'] = pd.to_datetime(weather_df['date'])

weather_df.head()

,STATION,NAME,date,AWND,PRCP,SNOW,SNWD,TMAX,TMIN
0,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2001-01-01,7.61,0.0,0.0,17.0,24,5
1,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2001-01-02,8.50,0.0,0.0,15.0,19,5
2,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2001-01-03,11.41,0.0,0.0,14.0,28,7
3,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2001-01-04,11.63,0.0,0.0,14.0,30,19
4,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2001-01-05,13.87,0.0,0.0,13.0,36,21

In [62]:
final_merged_df['date'] = pd.to_datetime(final_merged_df['Date']).dt.date

final_merged_df['date'] = pd.to_datetime(final_merged_df['date'])

final_merged_df[['Date', 'date']].head()

                  Date       date
0  2008-05-17 18:00:00 2008-05-17
1  2008-05-27 01:00:00 2008-05-27
2  2008-08-05 22:37:00 2008-08-05
3  2008-12-27 20:00:00 2008-12-27
4  2004-09-17 00:00:00 2004-09-17

In [63]:
final_merged_df = final_merged_df.merge(
    weather_df[['date', 'TMAX', 'TMIN', 'PRCP', 'SNOW', 'AWND']],
    on='date',
    how='left'
)

final_merged_df.head()

,ID,Date,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,community_area,...,community_name,per_capita_income,unemployment_rate,no_highschool_pct,date,TMAX,TMIN,PRCP,SNOW,AWND
0,6255892,2008-05-17 18:00:00,ROBBERY,ARMED - HANDGUN,RESIDENCE,0,0,511,5.0,49,...,Roseland,17949.0,20.3,16.9,2008-05-17,73,52,0.12,0.0,14.76
1,6272641,2008-05-27 01:00:00,ROBBERY,STRONG ARM - NO WEAPON,STREET,0,1,512,5.0,49,...,Roseland,17949.0,20.3,16.9,2008-05-27,50,42,0.00,0.0,19.24
2,6438609,2008-08-05 22:37:00,ROBBERY,ARMED - HANDGUN,SCHOOL - PUBLIC GROUNDS,0,0,523,5.0,53,...,West Pullman,16563.0,19.4,20.5,2008-08-05,87,69,0.00,0.0,7.38
3,6680276,2008-12-27 20:00:00,BURGLARY,FORCIBLE ENTRY,RESIDENCE - GARAGE,0,0,1622,16.0,11,...,Jefferson Park,27751.0,12.4,13.4,2008-12-27,61,32,1.74,0.0,17.67
4,13209443,2004-09-17 00:00:00,OFFENSE INVOLVING CHILDREN,AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,RESIDENCE,0,1,935,9.0,61,...,New City,12765.0,23.0,41.5,2004-09-17,70,53,0.00,0.0,8.28

In [64]:
final_merged_df[['TMAX', 'TMIN', 'PRCP', 'SNOW', 'AWND']].isnull().sum()

TMAX    0
TMIN    0
PRCP    0
SNOW    0
AWND    0
dtype: int64

In [65]:
final_merged_df['temp_avg'] = (final_merged_df['TMAX'] + final_merged_df['TMIN']) / 2

In [66]:
final_merged_df['is_rain'] = (final_merged_df['PRCP'] > 0).astype(int)

In [67]:
final_merged_df['is_snow'] = (final_merged_df['SNOW'] > 0).astype(int)

In [68]:
def temp_category(temp):
    if temp < 32:
        return 'cold'
    elif temp < 60:
        return 'mild'
    else:
        return 'hot'

final_merged_df['temp_category'] = final_merged_df['temp_avg'].apply(temp_category)

In [69]:
final_merged_df['high_wind'] = (final_merged_df['AWND'] > 15).astype(int)

In [70]:
final_merged_df.to_csv(
    r"D:\Data_D\TMU\MRP\1.0.Dataset\Final_Crime_Full_Features.csv",
    index=False
)

In [71]:
Main = pd.read_csv(r"D:\Data_D\TMU\MRP\1.0.Dataset\Final_Crime_Full_Features.csv")

In [72]:
Main.shape

(7970658, 33)