In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load Datasets

df_2012 = pd.read_csv(r"D:\Data_D\TMU\MRP\1.0.Dataset\Socio_Economic\Census_Data_-_Selected_socioeconomic_indicators_in_Chicago,_2008_–_2012_20260425.csv")
df_2020 = pd.read_csv(r"D:\Data_D\TMU\MRP\1.0.Dataset\Socio_Economic\Chicago_2020_sdoh.csv")

2008 - 2012

In [3]:
print(df_2012.shape)
print(df_2012.columns)

(78, 9)
Index(['Community Area Number', 'COMMUNITY AREA NAME',
       'PERCENT OF HOUSING CROWDED', 'PERCENT HOUSEHOLDS BELOW POVERTY',
       'PERCENT AGED 16+ UNEMPLOYED',
       'PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA',
       'PERCENT AGED UNDER 18 OR OVER 64', 'PER CAPITA INCOME ',
       'HARDSHIP INDEX'],
      dtype='object')

In [4]:
df_2012.tail()

,Community Area Number,COMMUNITY AREA NAME,PERCENT OF HOUSING CROWDED,PERCENT HOUSEHOLDS BELOW POVERTY,PERCENT AGED 16+ UNEMPLOYED,PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA,PERCENT AGED UNDER 18 OR OVER 64,PER CAPITA INCOME,HARDSHIP INDEX
73,74.0,Mount Greenwood,1.0,3.4,8.7,4.3,36.8,34381,16.0
74,75.0,Morgan Park,0.8,13.2,15.0,10.8,40.3,27149,30.0
75,76.0,O'Hare,3.6,15.4,7.1,10.9,30.3,25828,24.0
76,77.0,Edgewater,4.1,18.2,9.2,9.7,23.8,33385,19.0
77,NaN,CHICAGO,4.7,19.7,12.9,19.5,33.5,28202,NaN

In [5]:
df_2012 = df_2012.dropna(subset=['Community Area Number'])
print(df_2012.shape)

(77, 9)

In [6]:
df_2012.head()

,Community Area Number,COMMUNITY AREA NAME,PERCENT OF HOUSING CROWDED,PERCENT HOUSEHOLDS BELOW POVERTY,PERCENT AGED 16+ UNEMPLOYED,PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA,PERCENT AGED UNDER 18 OR OVER 64,PER CAPITA INCOME,HARDSHIP INDEX
0,1.0,Rogers Park,7.7,23.6,8.7,18.2,27.5,23939,39.0
1,2.0,West Ridge,7.8,17.2,8.8,20.8,38.5,23040,46.0
2,3.0,Uptown,3.8,24.0,8.9,11.8,22.2,35787,20.0
3,4.0,Lincoln Square,3.4,10.9,8.2,13.4,25.5,37524,17.0
4,5.0,North Center,0.3,7.5,5.2,4.5,26.2,57123,6.0

In [7]:
df_2012.tail()

,Community Area Number,COMMUNITY AREA NAME,PERCENT OF HOUSING CROWDED,PERCENT HOUSEHOLDS BELOW POVERTY,PERCENT AGED 16+ UNEMPLOYED,PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA,PERCENT AGED UNDER 18 OR OVER 64,PER CAPITA INCOME,HARDSHIP INDEX
72,73.0,Washington Height,1.1,16.9,20.8,13.7,42.6,19713,48.0
73,74.0,Mount Greenwood,1.0,3.4,8.7,4.3,36.8,34381,16.0
74,75.0,Morgan Park,0.8,13.2,15.0,10.8,40.3,27149,30.0
75,76.0,O'Hare,3.6,15.4,7.1,10.9,30.3,25828,24.0
76,77.0,Edgewater,4.1,18.2,9.2,9.7,23.8,33385,19.0

In [9]:
df_2012 = df_2012[[
    'Community Area Number',
    'COMMUNITY AREA NAME',
    'PER CAPITA INCOME ',
    'PERCENT AGED 16+ UNEMPLOYED',
    'PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA'
]]


df_2012.head(1)

,Community Area Number,COMMUNITY AREA NAME,PER CAPITA INCOME,PERCENT AGED 16+ UNEMPLOYED,PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA
0,1.0,Rogers Park,23939,8.7,18.2

In [10]:
df_2012 = df_2012.rename(columns={
    'Community Area Number': 'community_area',
    'COMMUNITY AREA NAME': 'community_name',
    'PER CAPITA INCOME ': 'per_capita_income',
    'PERCENT AGED 16+ UNEMPLOYED': 'unemployment_rate',
    'PERCENT HOUSEHOLDS BELOW POVERTY': 'poverty_rate',
    'PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA': 'no_highschool_pct'
})

df_2012.head(1)

,community_area,community_name,per_capita_income,unemployment_rate,no_highschool_pct
0,1.0,Rogers Park,23939,8.7,18.2

In [11]:
df_2012.dtypes

community_area       float64
community_name        object
per_capita_income      int64
unemployment_rate    float64
no_highschool_pct    float64
dtype: object

In [12]:
df_2012['community_area'] = df_2012['community_area'].astype(int)
print(df_2012.dtypes)
print(df_2012.shape)

community_area         int64
community_name        object
per_capita_income      int64
unemployment_rate    float64
no_highschool_pct    float64
dtype: object
(77, 5)

2020

In [13]:
print(df_2020.columns)
print(df_2020.shape)

Index(['area_num_1', 'community', 'shape_area', 'shape_len', 'districtno',
       'district', 'TOT_POP', '2000_POP', '2010_POP', 'UND5',
       ...
       'ARABIC', 'KOREAN', 'OTHASIAN', 'OTHER_EURO', 'OTHUNSPEC', '2000_WHITE',
       '2000_HISP', '2000_BLACK', '2000_ASIAN', '2000_OTHER'],
      dtype='object', length=232)
(77, 232)

In [14]:
print(df_2020['area_num_1'])
print(df_2020['community'])
print(df_2020['INCPERCAP'])
print(df_2020['Unemprt'])
print(df_2020['LT_HS'])
print(df_2020['TOT_POP'])

0     35
1     36
2     37
3     38
4     39
      ..
72    74
73    75
74    76
75    77
76     9
Name: area_num_1, Length: 77, dtype: int64
0             DOUGLAS
1             OAKLAND
2         FULLER PARK
3     GRAND BOULEVARD
4             KENWOOD
           ...
72    MOUNT GREENWOOD
73        MORGAN PARK
74              OHARE
75          EDGEWATER
76        EDISON PARK
Name: community, Length: 77, dtype: object
0     26096
1     23388
2     16519
3     29437
4     46785
      ...
72    40074
73    34873
74    31267
75    43457
76    59666
Name: INCPERCAP, Length: 77, dtype: int64
0     13.087248
1     15.328070
2     23.622047
3     13.743637
4     10.545867
        ...
72     4.064876
73    10.486669
74     5.208197
75     5.012482
76     1.558276
Name: Unemprt, Length: 77, dtype: float64
0     1514
1      404
2      373
3     2030
4      752
      ...
72     453
73    1051
74    1056
75    4123
76     362
Name: LT_HS, Length: 77, dtype: int64
0     21325
1      7227
2      2394
3     22209
4     17954
      ...
72    19190
73    21067
74    13075
75    57649
76    11111
Name: TOT_POP, Length: 77, dtype: int64

In [15]:
df_2020['no_highschool_pct'] = (df_2020['LT_HS']/ df_2020['TOT_POP'])*100
df_2020.head(1)

,area_num_1,community,shape_area,shape_len,districtno,district,TOT_POP,2000_POP,2010_POP,UND5,...,KOREAN,OTHASIAN,OTHER_EURO,OTHUNSPEC,2000_WHITE,2000_HISP,2000_BLACK,2000_ASIAN,2000_OTHER,no_highschool_pct
0,35,DOUGLAS,4.600462e+07,31027.05451,7,South Side,21325,26470,18238,1107,...,145,571,1290,555,1745,295,22635,1390,405,7.099648

In [16]:
df_2020 = df_2020[[
    'area_num_1',
    'community',
    'INCPERCAP',
    'Unemprt',
    'no_highschool_pct'
]]

df_2020.head(1)

   area_num_1 community  INCPERCAP    Unemprt  no_highschool_pct
0          35   DOUGLAS      26096  13.087248           7.099648

In [17]:
df_2020 = df_2020.rename(columns={
    'area_num_1': 'community_area',
    'community': 'community_name',
    'INCPERCAP': 'per_capita_income',
    'Unemprt': 'unemployment_rate'
})

df_2020.head()

,community_area,community_name,per_capita_income,unemployment_rate,no_highschool_pct
0,35,DOUGLAS,26096,13.087248,7.099648
1,36,OAKLAND,23388,15.328070,5.590148
2,37,FULLER PARK,16519,23.622047,15.580618
3,38,GRAND BOULEVARD,29437,13.743637,9.140439
4,39,KENWOOD,46785,10.545867,4.188482

In [18]:
df_2020.dtypes

community_area         int64
community_name        object
per_capita_income      int64
unemployment_rate    float64
no_highschool_pct    float64
dtype: object

In [19]:
df_2020.shape

(77, 5)

Adding Year Column to each dataset

In [20]:
df_2012['year'] = '2012'
df_2020['year'] = '2020'

df_2012.head(1)

,community_area,community_name,per_capita_income,unemployment_rate,no_highschool_pct,year
0,1,Rogers Park,23939,8.7,18.2,2012

In [21]:
df_2020.head(1)

,community_area,community_name,per_capita_income,unemployment_rate,no_highschool_pct,year
0,35,DOUGLAS,26096,13.087248,7.099648,2020

In [22]:
print(df_2012.shape)

print(df_2020.shape)

(77, 6)
(77, 6)

In [23]:
socio_economic = pd.concat([df_2012, df_2020], ignore_index=True)
socio_economic.head(1)

,community_area,community_name,per_capita_income,unemployment_rate,no_highschool_pct,year
0,1,Rogers Park,23939,8.7,18.2,2012

In [25]:
socio_economic["community_name"] = socio_economic["community_name"].str.lower().fillna("")

In [26]:
socio_economic.head(1)

,community_area,community_name,per_capita_income,unemployment_rate,no_highschool_pct,year
0,1,rogers park,23939,8.7,18.2,2012

In [27]:
socio_economic.tail(1)

,community_area,community_name,per_capita_income,unemployment_rate,no_highschool_pct,year
153,9,edison park,59666,1.558276,3.258033,2020

In [28]:
socio_economic.shape

(154, 6)

In [29]:
socio_economic = socio_economic.sort_values(by=['community_area', 'year'])
socio_economic.head(1)

,community_area,community_name,per_capita_income,unemployment_rate,no_highschool_pct,year
0,1,rogers park,23939,8.7,18.2,2012

In [30]:
socio_economic.tail(1)

,community_area,community_name,per_capita_income,unemployment_rate,no_highschool_pct,year
152,77,edgewater,43457,5.012482,7.151902,2020

In [31]:
socio_economic.shape

(154, 6)

In [32]:
socio_economic.columns

Index(['community_area', 'community_name', 'per_capita_income',
       'unemployment_rate', 'no_highschool_pct', 'year'],
      dtype='object')

In [33]:
socio_economic.dtypes

community_area         int64
community_name        object
per_capita_income      int64
unemployment_rate    float64
no_highschool_pct    float64
year                  object
dtype: object

In [34]:
socio_economic.to_csv(r"D:\Data_D\TMU\MRP\1.0.Dataset\Socio_Economic\Socio_Economic_Final.csv", index=False)